### ISSUE TITLE
Can't load static content

### ISSUE THREAD

**Issue by gridworkz** [beowulf1416/saas_old#5]
I'm new to Pyramid - I can't seem to load the static files after starting the server. Is there something I need to set? I've also set the path to the /static dir in ../../etc/nginx.conf. Cheers, Dave

**Comment by beowulf1416** [comment]
You need to set an instance of the configurator object to serve static content from a path somewhere. Something like this:
`config.add_static_view(name='static', path='/var/www/static')`
Refer to this doc in pyramid documentation.

**Comment by beowulf1416** [comment]
If you are using nginx to serve static content instead of pyramid... in the nginx configuration there should be a line similar to this:
`
location /static {
  root /path/to/static/files
}
`
the files will then be accessible via http://<<some_domain>>/static/<file>

**Comment by gridworkz** [comment]
Cool, thanks. Which .py file would I set the configurator object in? (config.add_static_view(name='static', path='/var/www/static'))

**Comment by beowulf1416** [comment]
> Cool, thanks. Which .py file would I set the configurator object in? (config.add_static_view(name='static', path='/var/www/static'))

disregard that. You updated the question when I was answering. I misunderstood your original question. Sorry.

**Comment by gridworkz** [comment]
Great, getting static content now. Going through nginx. Thanks

**Comment by beowulf1416** [comment]
Nice.
